//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OMV.rc
//
#define IDB_BUTTONS                     100
#define IDB_CLASS_VIEW                  101
#define IDB_CLASS_VIEW_24               102
#define IDB_EXPLORER_24                 103
#define IDB_FILE_VIEW                   104
#define IDB_FILE_VIEW_24                105
#define IDB_FILELARGE                   106
#define IDB_FILESMALL                   107
#define IDB_MAIN                        108
#define IDB_MENU_IMAGES_24              109
#define IDB_NAVIGATION_LARGE            110
#define IDB_NAVIGATION_LARGE_HC         111
#define IDB_PAGES                       112
#define IDB_PAGES_HC                    113
#define IDB_PAGES_SMALL                 114
#define IDB_PAGES_SMALL_HC              115
#define IDB_PROPERTIES_HC               116
#define IDB_SORT_24                     117
#define IDB_WRITELARGE                  118
#define IDB_WRITESMALL                  119
#define IDD_ABOUTBOX                    120
#define IDD_DIALOG_ANIMATION            121
#define IDI_CLASS_VIEW                  122
#define IDI_CLASS_VIEW_HC               123
#define IDI_FILE_VIEW                   124
#define IDI_FILE_VIEW_HC                125
#define IDI_OUTPUT_WND                  126
#define IDI_OUTPUT_WND_HC               127
#define IDR_MAINFRAME                   128
#define IDI_PROPERTIES_WND              129
#define IDI_PROPERTIES_WND_HC           130
#define IDR_EXPLORER                    131
#define IDR_MAINFRAME_256               132
#define IDR_MENU_IMAGES                 133
#define IDR_OgreModelConfigTYPE         134
#define IDR_OUTPUT_POPUP                135
#define IDR_PASTE_MENU                  136
#define IDR_POPUP_EDIT                  137
#define IDR_POPUP_EXPLORER              138
#define IDR_POPUP_SORT                  139
#define IDR_PROPERTIES                  140
#define IDR_SORT                        141
#define IDR_THEME_MENU                  142
#define IDR_WINDOWS_MENU                143
#define IDS_ACTOR_PANEL                 144
#define IDS_ANIMATION_VIEW              145
#define IDS_BUILD_TAB                   146
#define IDS_CALENDAR                    147
#define IDS_DEBUG_TAB                   148
#define IDS_EDIT_MENU                   149
#define IDS_EXPLORER                    150
#define IDS_FILE_VIEW                   151
#define IDS_FIND_TAB                    152
#define IDS_FOLDERS                     153
#define IDS_MESH_VIEW                   154
#define IDS_MYCALENDARS                 155
#define IDS_OUTLOOKBAR                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_RIBBON_CLIPBOARD            159
#define IDS_RIBBON_CLOSE                160
#define IDS_RIBBON_COPY                 161
#define IDS_RIBBON_CUT                  162
#define IDS_RIBBON_EXIT                 163
#define IDS_RIBBON_FILE                 164
#define IDS_RIBBON_HOME                 165
#define IDS_RIBBON_NEW                  166
#define IDS_RIBBON_OPEN                 167
#define IDS_RIBBON_OUTLOOKPANEL         168
#define IDS_RIBBON_PASTE                169
#define IDS_RIBBON_PRINT                170
#define IDS_RIBBON_PRINT_LABEL          171
#define IDS_RIBBON_PRINT_PREVIEW        172
#define IDS_RIBBON_PRINT_QUICK          173
#define IDS_RIBBON_PRINT_SETUP          174
#define IDS_RIBBON_RECENT_DOCS          175
#define IDS_RIBBON_SAVE                 176
#define IDS_RIBBON_SAVEAS               177
#define IDS_RIBBON_SCENE                178
#define IDS_RIBBON_SCENE_AXES           179
#define IDS_RIBBON_SCENE_BONES          180
#define IDS_RIBBON_SCENE_BOUDINGBOX     181
#define IDS_RIBBON_SCENE_FPS            182
#define IDS_RIBBON_SCENE_LOOKATMODE     183
#define IDS_RIBBON_SCENE_WIREFRAME      184
#define IDS_RIBBON_SELECTALL            185
#define IDS_RIBBON_STATUSBAR            186
#define IDS_RIBBON_STYLE                187
#define IDS_RIBBON_STYLE_DESC           188
#define IDS_RIBBON_STYLE_TIP            189
#define IDS_RIBBON_VIEW                 190
#define IDS_RIBBON_WINDOW               191
#define IDS_RIBBON_WINDOWS              192
#define IDS_SHORTCUTS                   193
#define IDS_STATUS_PANE1                194
#define IDS_STATUS_PANE2                195
#define IDS_VIEW_MESH_PANEL             196
#define IDS_VIEW_OUTPUT_PANEL           197
#define IDS_VIEW_PROPERTY_PANEL         198
#define IDS_WINDOWS_MANAGER             199
#define IDS_VIEW_ACTOR_PANEL            200
#define IDS_VIEW_ANIMATION_PANEL        201
#define IDC_BUTTON_PAUSE                1000
#define IDC_BUTTON_PLAY                 1001
#define IDC_BUTTON_STOP                 1002
#define IDC_CHECK_LOOP                  1003
#define IDC_COMBO_ANIMS                 1004
#define IDC_EDIT1                       1005
#define IDC_EDIT_SELECTED_BONE          1006
#define IDC_EDIT_SPEED                  1007
#define IDC_RADIO_LINEAR                1008
#define IDC_RADIO_SPLINE                1009
#define IDC_SLIDER_POS                  1010
#define IDC_TREE_DETAI                  1011
#define IDC_TREE_DETAILS                1012
#define ID_CLASS_ADD_MEMBER_FUNCTION    32771
#define ID_CLASS_ADD_MEMBER_VARIABLE    32772
#define ID_CLASS_DEFINITION             32773
#define ID_CLASS_PROPERTIES             32774
#define ID_DUMMY_COMPILE                32775
#define ID_EXPAND_ALL                   32776
#define ID_MESH_OPEN                    32777
#define ID_NEW_FOLDER                   32778
#define ID_OPEN                         32779
#define ID_OPEN_WITH                    32780
#define ID_PROPERTIES                   32781
#define ID_PROPERTIES1                  32782
#define ID_PROPERTIES2                  32783
#define ID_SCENE_LOOKATMODE             32784
#define ID_SCENE_SHOWAXES               32785
#define ID_SCENE_SHOWBONES              32786
#define ID_SCENE_SHOWBOUNDINGBOX        32787
#define ID_SCENE_SHOWFPS                32788
#define ID_SCENE_WIREFRAME              32789
#define ID_SET_STYLE                    32790
#define ID_SORT_MENU                    32791
#define ID_SORTING_GROUPBYTYPE          32792
#define ID_SORTING_SORTALPHABETIC       32793
#define ID_SORTING_SORTBYACCESS         32794
#define ID_SORTING_SORTBYTYPE           32795
#define ID_SORTPROPERTIES               32796
#define ID_STATUSBAR_PANE1              32797
#define ID_STATUSBAR_PANE2              32798
#define ID_TOOLS_MACRO                  32799
#define ID_VIEW_APPLOOK_OFF_2003        32800
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32801
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32802
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32803
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32804
#define ID_VIEW_APPLOOK_OFF_XP          32805
#define ID_VIEW_APPLOOK_VS_2005         32806
#define ID_VIEW_APPLOOK_WIN_2000        32807
#define ID_VIEW_APPLOOK_WIN_XP          32808
#define ID_VIEW_CLASSVIEW               32809
#define ID_VIEW_FILEVIEW                32810
#define ID_VIEW_OUTLOOK_BAR             32811
#define ID_VIEW_VIEW_ACTOR_PANEL        32812
#define ID_VIEW_VIEW_ANIMATION_PANEL    32813
#define ID_VIEW_VIEW_MESH_PANEL         32814
#define ID_VIEW_VIEW_OUTPUT_PANEL       32815
#define ID_VIEW_VIEW_PROPERTY_PANEL     32816
#define ID_WINDOW_MANAGER               32817
#define ID_WRITE_PASTEASHYPERLINK       32818

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           1113
#endif
#endif
